### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by vechicin** [vechicin/Cookbook#9]
There are two people in the group: @vechicin and @Lucas-Masaba.

[Here's](https://github.com/vechicin/Cookbook/projects/1) the link to the Kanban Board

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @vechicin and @Lucas-Masaba, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job setting up your Kanban board
- Your split the work fairly  

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
